[package]
name = "rustninja-websockets"
version = "0.1.0"
authors = ["David Haig <david@david>"]

[dependencies]
rust-crypto = "^0.2"
httparse = "^1.3.2"
base64 = "^0.9.2"
byteorder = "^1.2.6"
rand = "^0.5.5"
